In [ ]:
!pip -q install langchain langchain_community openai tiktoken sentence-transformers==2.2.2 requests==2.32.4 faiss-cpu pypdf python-docx ragas anthropic langchain-anthropic

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB 3.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 2.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 27.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 70.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 461.3/461.3 kB 32.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 82.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 343.9/343.9 kB 27.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 253.0/253.0 kB 21.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 466.5/466.5 kB 34.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 837.5/837.5 kB 48.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 3.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.5/66.5 kB 5.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 104.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 37.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 178.2/178.2 kB 14.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 360.7/360.7 kB 22.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.0/76.0 kB 6.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 83.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.0/51.0 kB 4.1 MB/s eta 0:00:00
  Building wheel for sentence-transformers (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
langgraph 1.2.1 requires langchain-core<2,>=1.4.0, but you have langchain-core 0.3.86 which is incompatible.
langgraph-prebuilt 1.1.0 requires langchain-core>=1.3.1, but you have langchain-core 0.3.86 which is incompatible.

In [ ]:
import os
from ragas import RunConfig

os.environ["RAGAS_DEBUG"] = "true"
run_config = RunConfig(timeout=120, log_tenacity=True)

/usr/local/lib/python3.12/dist-packages/google/colab/_import_hooks/_hook_injector.py:55: FutureWarning:

All support for the `google.generativeai` package has ended. It will no longer be receiving
updates or bug fixes. Please switch to the `google.genai` package as soon as possible.
See README for more details:

https://github.com/google-gemini/deprecated-generative-ai-python/blob/main/README.md

  loader.exec_module(module)

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

Mounted at /content/gdrive

In [ ]:
from langchain.vectorstores import FAISS
from langchain.embeddings.openai import OpenAIEmbeddings

# Supply OPENAI_API_KEY through the environment; never save credentials in this notebook.

In [ ]:
vectorstorepath = f"work/indexes/worringer_index"
answerpath = f"GPT_4o_extractions_full_pipe/worringer_extraction_4o"
groundtruthpath = f"Annotations/worringer.docx"

In [ ]:
openai_embeddings = OpenAIEmbeddings()

# Load FAISS
KB = FAISS.load_local(
    vectorstorepath,
    openai_embeddings,
    allow_dangerous_deserialization=True
)
chunks = KB.index.ntotal
#chunks = chunks/1
#chunks=62
retriever = KB.as_retriever(search_kwargs={"k": chunks})
print(f"Number of Chunks in VDB: {chunks}")

/tmp/ipykernel_1800/3468371221.py:1: LangChainDeprecationWarning: The class `OpenAIEmbeddings` was deprecated in LangChain 0.0.9 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-openai package and should be used instead. To use it run `pip install -U :class:`~langchain-openai` and import as `from :class:`~langchain_openai import OpenAIEmbeddings``.
  openai_embeddings = OpenAIEmbeddings()

Number of Chunks in VDB: 10

In [ ]:
import re
from docx import Document

doc = Document(answerpath)
full_text = []

# paragraphs
for para in doc.paragraphs:
    full_text.append(para.text)

# tables
for table in doc.tables:
    for row in table.rows:
        cells = [cell.text.strip() for cell in row.cells]
        full_text.append(" | ".join(cells))
        full_text.append("")

answer = "\n".join(full_text)
answer = re.sub(r'[*,-]', '', answer)

In [ ]:
doc = Document(groundtruthpath)
gt_text = []

for para in doc.paragraphs:
    gt_text.append(para.text)

for table in doc.tables:
    for row in table.rows:
        cells = [cell.text.strip() for cell in row.cells]
        gt_text.append(" | ".join(cells))
        gt_text.append("")

groundtruth = "\n".join(gt_text)

In [ ]:
query = '''Provide a comprehensive structured summary of the Women’s Health Initiative (WHI) randomized controlled trial evaluating hormone therapy in postmenopausal women.

Include the following required fields:

Study Methods

Study design

Allocation concealment

Blinding

Setting

Sample size

Duration of follow-up

Whether intention-to-treat analysis was performed

Population

Inclusion criteria

Key exclusion criteria

Baseline characteristics (mean age, sex distribution, race/ethnicity)

Intervention

Hormone therapy regimen(s), dosage, and group size

Comparator

Description of placebo or control group

Outcomes

Primary outcomes

Secondary outcomes

Adverse events

Main Results (Statistical Data Required)
For each outcome, report:

Outcome type

Outcome description

Time point or subgroup

Effect size (HR or RR) with 95% confidence interval

Comparison interpretation

Sources of Funding

Overall Conclusion and Clinical Recommendation'''

In [ ]:
retrieved_docs = retriever.get_relevant_documents(query)
context = [doc.page_content for doc in retrieved_docs]

/tmp/ipykernel_1800/3072982058.py:1: LangChainDeprecationWarning: The method `BaseRetriever.get_relevant_documents` was deprecated in langchain-core 0.1.46 and will be removed in 1.0. Use :meth:`~invoke` instead.
  retrieved_docs = retriever.get_relevant_documents(query)

In [ ]:
print(context[0])

In [ ]:
from datasets import Dataset
data = {
    "question": [query],
    "answer": [answer],
    "contexts": [context],
    "ground_truth": [groundtruth]
}
dataset1 = Dataset.from_dict(data)

In [ ]:
from ragas import evaluate
from ragas.metrics import (
    faithfulness,
    context_recall,
    #answer_relevancy
)

import nest_asyncio
nest_asyncio.apply()

/tmp/ipykernel_1800/367557245.py:2: DeprecationWarning: Importing faithfulness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import faithfulness
  from ragas.metrics import (
/tmp/ipykernel_1800/367557245.py:2: DeprecationWarning: Importing context_recall from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import context_recall
  from ragas.metrics import (

In [ ]:
from langchain_anthropic import ChatAnthropic
# Supply ANTHROPIC_API_KEY through the environment; never save credentials in this notebook.

claude_3_haiku = ChatAnthropic(
    model="claude-3-haiku-20240307",
    max_tokens=4096,
    temperature=0.2
)

In [ ]:
from langchain.chat_models import ChatOpenAI
gpt_5_1 = ChatOpenAI(model_name='gpt-5.1')

/tmp/ipykernel_1800/118763364.py:2: LangChainDeprecationWarning: The class `ChatOpenAI` was deprecated in LangChain 0.0.10 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-openai package and should be used instead. To use it run `pip install -U :class:`~langchain-openai` and import as `from :class:`~langchain_openai import ChatOpenAI``.
  gpt_5_1 = ChatOpenAI(model_name='gpt-4.1-mini')

In [ ]:
try:
    result = evaluate(
        llm=gpt_5_1,
        dataset=dataset1,
        raise_exceptions=False,
        metrics=[faithfulness,context_recall],
    )

    df = result.to_pandas()


except KeyError as e:
    print("Error during evaluation:", e)

Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]

In [ ]:
df #worringer

,user_input,retrieved_contexts,response,faithfulness
0,Provide a comprehensive structured summary of ...,[Research Original Investigation\nAcetaminophe...,PICO variables\n1. Methods\n Design: Nation...,0.903846

In [ ]:
df #wilken

,user_input,retrieved_contexts,response,faithfulness
0,Provide a comprehensive structured summary of ...,[Articles\nResearch in context\nEvidence befor...,PICO variables\n1. Methods\n Design: Random...,1.0

In [ ]:
df #visva

,user_input,retrieved_contexts,response,faithfulness
0,Provide a comprehensive structured summary of ...,[USPSTF Recommendation: Screening for Breast C...,PICO variables\nThis response is based on the ...,1.0

In [ ]:
df #tanner

,user_input,retrieved_contexts,response,faithfulness
0,Provide a comprehensive structured summary of ...,[Research Original Investigation\nOpt-Out vs O...,PICO variables\n1. Methods\n Design: Random...,1.0

In [ ]:
df #parks

,user_input,retrieved_contexts,response,faithfulness
0,Provide a comprehensive structured summary of ...,[RESEARCH\n.\nat Birmingham City University\n ...,PICO variables\n1. Methods\n Design: Nation...,0.983607

In [ ]:
df #ott

,user_input,retrieved_contexts,response,faithfulness
0,Provide a comprehensive structured summary of ...,[Clinical Review & Education US Preventive Ser...,PICO variables\n1. Methods\n Design: Random...,0.977011

In [ ]:
df #maki

,user_input,retrieved_contexts,response,faithfulness
0,Provide a comprehensive structured summary of ...,[USPSTF Recommendation: Screening for Asymptom...,PICO variables\nThe provided text is a summary...,1.0

In [ ]:
df #kabo

,user_input,retrieved_contexts,response,faithfulness
0,Provide a comprehensive structured summary of ...,[Articles\n187 473 women invited\n171 063 no r...,PICO variables\n1. Methods\n Design: Random...,1.0

In [ ]:
df #haung

,user_input,retrieved_contexts,response,faithfulness
0,Provide a comprehensive structured summary of ...,[Articles\npost-baseline visit. Baseline demog...,PICO variables\n1. Methods\n Design: Random...,0.914286

In [ ]:
df #buden

,user_input,retrieved_contexts,response,faithfulness
0,Provide a comprehensive structured summary of ...,[USPSTF Recommendation: Screening for Preeclam...,PICO variables\nThe information provided does ...,1.0

In [ ]:
df #batur

,user_input,retrieved_contexts,response,faithfulness
0,Provide a comprehensive structured summary of ...,[Self-Sampling Strategy to Increase Cervical C...,PICO variables\n1. Methods\n Design: Random...,0.966667

In [ ]:
df # batur 2025

,user_input,retrieved_contexts,response,faithfulness
0,Provide a comprehensive structured summary of ...,[RESEARCH\nRESEARCH\n.\nat Birmingham City Uni...,PICO variables\n1. Methods\n Design: Nation...,0.986111

In [ ]:
df #batur 2025 4

,user_input,retrieved_contexts,response,faithfulness
0,Provide a comprehensive structured summary of ...,[RESEARCH\nRESEARCH\n.\nat Birmingham City Uni...,PICO variables\n1. Methods\n Design: Nation...,NaN

In [ ]:
df #batur 2023

,user_input,retrieved_contexts,response,faithfulness
0,Provide a comprehensive structured summary of ...,"[Articles\ntest was carried out, and a positiv...",PICO variables\n1. Methods\n Design: Random...,0.90991

In [ ]:
df #batur 2021

,user_input,retrieved_contexts,response,faithfulness
0,Provide a comprehensive structured summary of ...,[Articles\nscreening in a 1:1:2 ratio. The tri...,PICO variables\n1. Methods\n Design: Random...,0.977778

In [ ]:
df #12th

,user_input,retrieved_contexts,response,faithfulness
0,Provide a comprehensive structured summary of ...,[Cochrane\nLibrary\nTrusted evidence.\nInforme...,PICO variables\nCertainly! Below is a structur...,1.0

In [ ]:
df #11th

,user_input,retrieved_contexts,response,faithfulness
0,Provide a comprehensive structured summary of ...,[Exemestane to Prevent Breast Cancer\ntectomy....,PICO variables\n1. Methods\n Design: Random...,1.0

In [ ]:
df #10th

,user_input,retrieved_contexts,response,faithfulness
0,Provide a comprehensive structured summary of ...,[BMJ 2012;345:e6409 doi: 10.1136/bmj.e6409 (Pu...,PICO variables\n1. Methods\n Design: Random...,0.983051

In [ ]:
df #9th

,user_input,retrieved_contexts,response,faithfulness
0,Provide a comprehensive structured summary of ...,"[14710528, 2017, 10, Downloaded from https://o...",PICO variables\n1. Methods\n Design: System...,0.962963

In [ ]:
df #8th

,user_input,retrieved_contexts,response,faithfulness
0,Provide a comprehensive structured summary of ...,[Chlebowski et al.\nPage 3\nAll women in both ...,PICO variables\n1. Methods\n Design: Random...,0.981481

In [ ]:
df #6th

,user_input,retrieved_contexts,response,faithfulness
0,Provide a comprehensive structured summary of ...,[Maalouf et al.\nPage 14\nIncidence (Annualize...,PICO variables\n1. Methods\n Design: Random...,0.969697

In [ ]:
df #5th

,user_input,retrieved_contexts,response,faithfulness
0,Provide a comprehensive structured summary of ...,[Cochrane\nLibrary\nTrusted evidence.\nInforme...,PICO variables\nTo address the question using ...,0.984375

In [ ]:
df #4th

,user_input,retrieved_contexts,response,faithfulness
0,Provide a comprehensive structured summary of ...,[Manson et al.\nPage 19\nTable\nBaseline Chara...,PICO variables\n1. Methods\n Design: Random...,1.0

In [ ]:
df # 3rd

,user_input,retrieved_contexts,response,faithfulness
0,Provide a comprehensive structured summary of ...,[McCurry et al.\nPage 5\ncontacted by telephon...,PICO variables\n1. Methods\n Design: Random...,0.931818

In [ ]:
df #3rd

,user_input,retrieved_contexts,response,faithfulness
0,Provide a comprehensive structured summary of ...,[McCurry et al.\nPage 5\ncontacted by telephon...,PICO variables\n1. Methods\n Design: Random...,1.0

In [ ]:
df #2nd

,user_input,retrieved_contexts,response,faithfulness
0,Provide a comprehensive structured summary of ...,[Canonico et al Hormone Therapy and Stroke ...,PICO variables\n1. Methods\n Design: Nested...,1.0

In [ ]:
df #2nd

,user_input,retrieved_contexts,response,faithfulness
0,Provide a comprehensive structured summary of ...,[Canonico et al Hormone Therapy and Stroke ...,PICO variables\n1. Methods\n Design: Nested...,0.864198

In [ ]:
print(len(df['retrieved_contexts']))

1

In [ ]:
for x in df['retrieved_contexts']:
  print(x)

['Clinical Review & Education US Preventive Services Task Force\nUSPSTF Recommendation Statement: Hormone Therapy After Menopause\nFigure 1. US Preventive Services Task Force (USPSTF) Grades and Levels of Certainty\nWhat the USPSTF Grades Mean and Suggestions for Practice\nGrade\nDefinition\nSuggestions for Practice\nA\nThe USPSTF recommends the service. There is high certainty that the net benefit is substantial.\nOffer or provide this service.\nB\nThe USPSTF recommends the service. There is high certainty that the net benefit is moderate, or\nthere is moderate certainty that the net benefit is moderate to substantial.\nOffer or provide this service.\nC\nThe USPSTF recommends selectively offering or providing this service to individual patients\nbased on professional judgment and patient preferences. There is at least moderate certainty\nthat the net benefit is small.\nOffer or provide this service for selected\npatients depending on individual\ncircumstances.\nD\nThe USPSTF recommends against the service. There is moderate or high certainty that the service\nhas no net benefit or that the harms outweigh the benefits.\nDiscourage the use of this service.\nThe USPSTF concludes that the current evidence is insufficient to assess the balance of benefits\nand harms of the service. Evidence is lacking, of poor quality, or conflicting, and the balance of\nbenefits and harms cannot be determined.\nRead the Clinical Considerations section\nof the USPSTF Recommendation\nStatement. If the service is offered,\npatients should understand the\nuncertainty about the balance of benefits\nand harms.\nI statement\nUSPSTF Levels of Certainty Regarding Net Benefit\nLevel of Certainty\nDescription\nHigh\nThe available evidence usually includes consistent results from well-designed, well-conducted studies in representative primary care\npopulations. These studies assess the effects of the preventive service on health outcomes. This conclusion is therefore unlikely to be\nstrongly affected by the results of future studies.\nThe available evidence is sufficient to determine the effects of the preventive service on health outcomes, but confidence in the estimate\nis constrained by such factors as \nthe number, size, or quality of individual studies.\ninconsistency of findings across individual studies.\nlimited generalizability of findings to routine primary care practice.\nlack of coherence in the chain of evidence.\nAs more information becomes available, the magnitude or direction of the observed effect could change, and this change may be large\nenough to alter the conclusion.\nModerate\nThe available evidence is insufficient to assess effects on health outcomes. Evidence is insufficient because of\nthe limited number or size of studies.\nimportant flaws in study design or methods.\ninconsistency of findings across individual studies.\ngaps in the chain of evidence.\nfindings not generalizable to routine primary care practice.\nlack of information on important health outcomes.\nMore information may allow estimation of effects on health outcomes.\nLow\nThe USPSTF defines certainty as “likelihood that the USPSTF assessment of the net benefit of a preventive service is correct.” The net benefit is defined as\nbenefit minus harm of the preventive service as implemented in a general, primary care population. The USPSTF assigns a certainty level based on the nature\nof the overall evidence available to assess the net benefit of a preventive service.\norwithout2.5mg/dofmedroxyprogesteroneacetate.Currently,evi-\ndencetodeterminewhetherdifferenttypes,doses,ormodesofde-\nlivery of hormone therapy affect its benefit-to-harm profile for the\nprevention of chronic conditions is limited.1\n(eg,creamsorrings)ofhormonetherapy,becausethesearenotgen-\nerally used for the primary prevention of chronic conditions.\nIndicationsforhormonetherapyapprovedbytheUSFoodand\nDrugAdministration(FDA)inmenopausalwomenarelimitedtothe\ntreatment of menopausal symptoms and the prevention of post-\nmenopausal osteoporosis. An FDA-issued black box warning indi-\ncates that estrogen therapy, with or without progestin, should be\nprescribed at the lowest effective dose and for the shortest dura-\ntion consistent with the patient’s treatment goals and risks.2\nTheuseofmenopausalhormonetherapyisassociatedwithboth\nbenefitsandharms.Combinedestrogenandprogestinuseisassociated\nwithadecreasedriskoffractures,diabetes,andcolorectalcancer;how-\never,itisalsoassociatedwithanincreasedriskofinvasivebreastcancer,\ncoronary heart disease, thromboembolic events, stroke, dementia,\ngallbladderdisease,andself-reportedurinaryincontinence.Estrogen\nusealoneisassociatedwithadecreasedriskoffractures,invasivebreast\ncancer, and diabetes; however, it is also associated with an increased\nriskofthromboembolicevents,stroke,dementia,gallbladderdisease,\nSeveraldifferentformulationsofmenopausalhormonetherapy\nare approved by the FDA for use in the United States; the specific\nformulation used in the WHI trial, the largest trial reviewed by the\nUSPSTF,was0.625mg/doforalconjugatedequineestrogens,with\n2226\nJAMA\nDecember 12, 2017\nVolume 318, Number 22\n(Reprinted)\njama.com\n© 2017 American Medical Association. All rights reserved.\nDownloaded From:  by a University of California - Los Angeles User  on 08/17/2018\n\nGrade\tDefinition\tSuggestions for Practice\nA\tThe USPSTF recommends the service. There is high certainty that the net benefit is substantial.\tOffer or provide this service.\nB\tThe USPSTF recommends the service. There is high certainty that the net benefit is moderate, or\nthere is moderate certainty that the net benefit is moderate to substantial.\tOffer or provide this service.\nC\tThe USPSTF recommends selectively offering or providing this service to individual patients\nbased on professional judgment and patient preferences. There is at least moderate certainty\nthat the net benefit is small.\tOffer or provide this service for selected\npatients depending on individual\ncircumstances.\nD\tThe USPSTF recommends against the service. There is moderate or high certainty that the service\nhas no net benefit or that the harms outweigh the benefits.\tDiscourage the use of this service.\nI statement\tThe USPSTF concludes that the current evidence is insufficient to assess the balance of benefits\nand harms of the service. Evidence is lacking, of poor quality, or conflicting, and the balance of\nbenefits and harms cannot be determined.\tRead the Clinical Considerations section\nof the USPSTF Recommendation\nStatement. If the service is offered,\npatients should understand the\nuncertainty about the balance of benefits\nand harms.\n\nLevel of Certainty\tDescription\nHigh\tThe available evidence usually includes consistent results from well-designed, well-conducted studies in representative primary care\npopulations. These studies assess the effects of the preventive service on health outcomes. This conclusion is therefore unlikely to be\nstrongly affected by the results of future studies.\nModerate\tThe available evidence is sufficient to determine the effects of the preventive service on health outcomes, but confidence in the estimate\nis constrained by such factors as\nthe number, size, or quality of individual studies.\ninconsistency of findings across individual studies.\nlimited generalizability of findings to routine primary care practice.\nlack of coherence in the chain of evidence.\nAs more information becomes available, the magnitude or direction of the observed effect could change, and this change may be large\nenough to alter the conclusion.\nLow\tThe available evidence is insufficient to assess effects on health outcomes. Evidence is insufficient because of\nthe limited number or size of studies.\nimportant flaws in study design or methods.\ninconsistency of findings across individual studies.\ngaps in the chain of evidence.\nfindings not generalizable to routine primary care practice.\nlack of information on important health outcomes.\nMore information may allow estimation of effects on health outcomes.\nThe USPSTF defines certainty as “likelihood that the USPSTF assessment of the net benefit of a preventive service is correct.” The net benefit is defined as\nbenefit minus harm of the preventive service as implemented in a general, primary care population. The USPSTF assigns a certainty level based on the nature\nof the overall evidence available to assess the net benefit of a preventive service.\t\n', 'UCLA\nUCLA Previously Published Works\nTitle\nHormone Therapy for the Primary Prevention of Chronic Conditions in Postmenopausal\nWomen: US Preventive Services Task Force Recommendation Statement\nPermalink\nhttps://escholarship.org/uc/item/73b1r768\nJournal\nJAMA: The Journal of the American Medical Association, 318(22)\nISSN\n0098-7484\nAuthors\nGrossman, David C\nCurry, Susan J\nOwens, Douglas K\net al.\nPublication Date\n2017-12-12\nDOI\n10.1001/jama.2017.18261\nScholarly article\neScholarship.org\nPowered by the California Digital Library\nUniversity of California\n', 'USPSTF Recommendation Statement: Hormone Therapy After Menopause\nUS Preventive Services Task Force Clinical Review & Education\nduringameanfollow-upof6.8years.1ArecentWHIanalysisshowed\nnosignificantdifferenceinall-causemortalitybetweenwomenran-\ndomized to combined estrogen and progestin (HR, 1.02 [95% CI,\n0.96-1.08])orestrogenalone(HR,0.94[95%CI,0.88-1.01])vspla-\ncebo during 18 years of cumulative follow-up.31\nTo date, no good-quality randomized trials have prospectively\nevaluated the effect of timing of hormone therapy initiation rela-\ntive to the onset of menopause on associated benefits and harms.\nEstimate of Magnitude of Net Benefit\nAlthough the use of hormone therapy to prevent chronic condi-\ntions in postmenopausal women is associated with some benefits,\ntherearealsowell-documentedharms.TheUSPSTFdeterminedthat\nthe magnitude of both the benefits and the harms of hormone\ntherapy in postmenopausal women is small to moderate. There-\nfore, the USPSTF concludes with moderate certainty that com-\nbinedestrogenandprogestinhasnonetbenefitfortheprimarypre-\nventionofchronicconditionsinmostpostmenopausalwomenwith\nan intact uterus and that estrogen alone has no net benefit for the\nprimary prevention of chronic conditions in most postmenopausal\nwomen who have had a hysterectomy.\nSubgroups of Interest\nSubgroups of interest for this recommendation statement include\nwomen grouped according to race/ethnicity; age; duration of hor-\nmone therapy use; type, dose, and mode of delivery of hormone\ntherapy; and presence of comorbid conditions.\nTrials did not report results for most of these subgroups.\nSubgroup analyses were limited to those based on race/ethnicity,\nage, and a small number of comorbid conditions or risk factors.\nFor most outcomes, there were no statistically significant sub-\ngroup effects; however, studies may have been underpowered to\ndetect such effects.\nIn the WHI estrogen-alone trial, statistically significant interac-\ntionsbetweenageandtheriskofall-causemortality,colorectalcan-\ncer, and myocardial infarction, though not total coronary heart dis-\nease events, were detected. There were significant trends toward\nlowerrisksoftheseoutcomesinyoungerwomen(50-59years)and\nhigher risks in older women (70-79 years) randomized to estrogen\nalone relative to placebo.13 However, the multiplicity of outcomes\nand subgroup comparisons conducted (in these analyses, P values\nfor trend by age group were not adjusted for the large number of\ntests conducted), as well as the small number of events that oc-\ncurred for some of these outcomes in the estrogen-alone trial sub-\ngroups,limitthestrengthofthesefindings.Theselimitations,along\nwith the absence of significant subgroup effects for most out-\ncomes, led the USPSTF to conclude that the evidence was inad-\nequate to determine that any subgroup had a different balance of\nbenefits and harms.\nTodate,evidencetodeterminewhetherdifferenttypes,doses,\nor modes of delivery of hormone therapy have a different balance\nof benefits and harms is limited.\nHow Does Evidence Fit With Biological Understanding?\nTraditionally, estrogen has been viewed as having cardioprotective\neffects. The incidence of coronary heart disease in premenopausal\nwomen is lower than in men of the same age; this difference de-\ncreases as women age past menopause. Estrogen decreases\nlevels of low-density lipoprotein cholesterol, increases levels of\nhigh-densitylipoproteincholesterol,andhasavasodilatoreffect.De-\nspite these observations, data from randomized clinical trials show\na lack of benefit, or even a harmful effect, of hormone therapy on\nrisk of coronary heart disease in postmenopausal women. Several\npotential factors, including timing of initiation of hormone therapy\nwith respect to menopause, older age, and presence of atheroma,\nhavebeenproposedtoaccountforthesediscrepantfindings.None-\ntheless, the underlying causes of this lack of benefit are uncertain.\nAnother discrepant finding is that combined estrogen and\nprogestin is associated with a small increase in the risk of breast\ncancer, while estrogen alone appears to slightly reduce this risk.\nAlthoughestrogengenerallystimulatesbreastcellproliferation,some\npreclinical studies have shown that estrogen can induce breast cell\napoptosis if administered under conditions of estrogen depriva-\ntion, and that progestin can stimulate breast cell proliferation and\nformation of new blood vessels. These findings have been pro-\nposedasapossibleexplanationfortheapparentdiscrepanteffects\nof combined estrogen and progestin and estrogen alone on breast\ncancer risk.32\nTiming of Preventive Medication\nIt has been proposed that hormone therapy initiated closer to the\ntime of menopause may have a more beneficial, or less deleteri-\nous, effect on risk of coronary heart disease (and possibly other\nhealth outcomes) than hormone therapy initiated later; this pro-\nposal has been termed the timing hypothesis. Findings from post\nhoc subgroup analyses of the WHI trial regarding the effect of tim-\ning of hormone therapy initiation on the risk of coronary events are\nconflicting. In 1 subgroup analysis, women randomized to com-\nbinedestrogenandprogestinwithin10yearsofmenopausedidnot\nhavetheincreasedriskofcoronaryheartdiseaseobservedinwomen\nrandomized to hormone therapy more than 20 years postmeno-\npause; however, there was also no beneficial effect in the former\ngroup.Incontrast,asecondsubgroupanalysisthatconsideredprior\nhormone therapy use (ie, before trial enrollment), which provides\na more accurate assessment of the time between menopause and\ninitiation of hormone therapy, found no difference in coronary risk\nbetween early (<5 years) vs late (5 years) initiation of hormone\ntherapy.Itisimportanttonotethatallsuchposthocanalysesshould\nbe considered exploratory (hypothesis forming) and not confirma-\ntory in nature, and are also subject to potential bias.\nResponse to Public Comment\nA draft version of this recommendation statement was posted for\npublic comment on the USPSTF website from May 16 to June 12,\n2017.Inresponsetopubliccomment,theUSPSTFmodifiedthetitle\nof the recommendation statement to clarify that the patient popu-\nlationunderconsiderationconsistsofpostmenopausalwomen.The\nUSPSTF clarified that it reviewed the evidence on the benefits and\nharms of systemic menopausal hormone therapy (ie, administered\norally or transdermally), not local hormone therapy (eg, creams or\nrings). The USPSTF also provided additional details about the WHI\ntrial, specifying the formulation of hormone therapy used and the\naverage age of women enrolled in the trial. The USPSTF added 2\ntables showing the absolute risk increase or decrease of various\nhealth outcomes in women receiving combined estrogen and pro-\ngestin or estrogen alone (Table 1 and Table 2).\njama.com\n(Reprinted)\nJAMA\nDecember 12, 2017\nVolume 318, Number 22\n2231\n© 2017 American Medical Association. All rights reserved.\nDownloaded From:  by a University of California - Los Angeles User  on 08/17/2018\n', 'Clinical Review & Education US Preventive Services Task Force\nUSPSTF Recommendation Statement: Hormone Therapy After Menopause\n0.63-1.01]).13 In HERS, there were fewer cases of colorectal cancer\nin women randomized to combined estrogen and progestin (vs pla-\ncebo) over a mean duration of 4.1 years, but the results were not\nstatistically significant (HR, 0.69 [95% CI, 0.32-1.49]).14 EMS21 and\nthe WISDOM18 trial reported no statistically significant differences\nin risk of colorectal cancer. However, event rates in these studies\nwere low, and the length of follow-up was short (<2 years), which\nprecluded these studies from being combined with the WHI trial\nand HERS in a meta-analysis.\nThe WHI trial reported no significant difference in the inci-\ndence of colorectal cancer between women randomized to estro-\ngen alone vs placebo during the intervention phase (HR, 1.15 [95%\nCI,0.81-1.64])orthecumulativefollow-upperiod(HR,1.13[95%CI,\n0.85-1.51]).13\nUrinary Incontinence\nBoththeWHItrialandHERSshowedaconsistentlyhigherriskofself-\nreported incident urinary incontinence at all time points in women\nwho took combined estrogen and progestin vs placebo. In the WHI\ntrial, women who took combined estrogen and progestin had a\nhigherriskofincontinenceat1year(RR,1.39[95%CI,1.27-1.52])and\nat3years(RR,1.81[95%CI,1.16-2.84]).25InHERS,womenwhotook\ncombined estrogen and progestin had a higher risk of incontinence\nat the 4.2-year follow-up (odds ratio, 1.6 [95% CI, 1.3-1.9]).26\nTwo trials, WHI25 and Ultra Low Dose Transdermal Estrogen\nAssessment(ULTRA),27provideddataonself-reportedincidenturi-\nnary incontinence in women who took estrogen alone vs placebo.\nIn the WHI trial, women who took estrogen alone had an increased\nriskofurinaryincontinencevsthosewhoreceivedplaceboat1year\n(RR, 1.53 [95% CI, 1.37-1.71]); results based on smaller samples at 2\n(ULTRA) and 3 (WHI) years of treatment did not show any signifi-\ncant differences in incident urinary incontinence.\nOther Types of Cancer\nBoth the WHI trial13 and HERS14 showed no significant difference\nin the incidence of lung cancer in women who received combined\nestrogen and progestin vs placebo during the intervention phase\nand postintervention follow-up. EMS21 reported only 1 case of\nlung cancer, in the hormone therapy group, and its short trial pe-\nriod precluded it from being combined with the WHI trial and HERS\nin a meta-analysis.\nThe WHI trial reported no significant difference in lung cancer\nincidencebetweenwomenwhoreceivedestrogenaloneandwomen\nwhoreceivedplacebo,bothduringtheinterventionphaseandpost-\nintervention follow-up.13\nFractures\nPooled results of 5 trials (N = 20 499) showed a significantly re-\nduced risk of fractures in women randomized to combined estro-\ngen and progestin vs placebo (RR, 0.80 [95% CI, 0.68-0.94]).1\nTheWHItrialshowedasignificantlyreducedriskoftotalosteo-\nporotic fractures in women randomized to estrogen alone vs pla-\ncebo (HR, 0.72 [95% CI, 0.64-0.80]).13 The difference was no\nlonger statistically significant in the postintervention phase (dura-\ntion,10.7years);however,thisstudyreportedonlyonhipfractures.12\nIntheWHItrial13andHERS,14theincidenceofendometrialcan-\ncer during the intervention phase did not differ significantly be-\ntween women who received combined estrogen and progestin vs\nplacebo. During the WHI postintervention period, statistically sig-\nnificantlyfewerwomenrandomizedtohormonetherapyduringthe\ntrialphasedevelopedendometrialcancer(HR,0.58[95%CI,0.40-\n0.86])thandidwomenwhoreceivedplacebo.13Twoadditionaltrials,\nERA15 and PEPI,16 reported no cases of endometrial cancer; how-\never,thetrialsweretooshorttobecombinedwiththeWHItrialand\nHERS in a meta-analysis.\nIn the WHI trial, there was no significant difference in the 

In [ ]:
try:
    result = evaluate(
        llm=claude_3_haiku,
        dataset=dataset1,
        raise_exceptions=False,
        metrics=[faithfulness],
    )

    df = result.to_pandas()


except KeyError as e:
    print("Error during evaluation:", e)

Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

ERROR:ragas.executor:Exception raised in Job[0]: OutputParserException(Invalid json output: {
    "statements": [
        {
            "statement": "The study was a randomized controlled trial.",
            "reason": "The study design is clearly described as "randomized, double-blind, multinational, and placebo-controlled trials".",
            "verdict": 1
        },
        {
            "statement": "The study used a centralized interactive voice/web response system for randomization which indicates allocation concealment.",
            "reason": "The study states that "Randomization was performed centrally using an interactive voice/web response system and stratified by North America and the rest of the countries."",
            "verdict": 1
        },
        {
            "statement": "Investigators, participants, and study personnel remained blinded throughout the trials.",
            "reason": "The study explicitly states that "Investigators, participants, and study personnel remained blinded throughout the trials."",
            "verdict": 1
        },
        {
            "statement": "The followup duration was 26 weeks.",
            "reason": "The study design states that the trials were "26-week intervention trials".",
            "verdict": 1
        },
        {
            "statement": "The study was conducted at 77 sites in the US, Europe, and Israel for OASIS 1, and 77 sites in the US, Canada, and Europe for OASIS 2.",
            "reason": "The study states that "OASIS 1 was conducted between August 27, 2021, and November 27, 2023, across 77 sites in the US, Europe, and Israel. OASIS 2 was conducted between October 29, 2021, and October 10, 2023, across 77 sites in Canada, the US, and Europe."",
            "verdict": 1
        },
        {
            "statement": "The sample size was 796 participants (OASIS 1: 396; OASIS 2: 400).",
            "reason": "The study states that "400 Randomized" for OASIS 2 and "396 Randomized" for OASIS 1, totaling 796 participants.",
            "verdict": 1
        },
        {
            "statement": "The inclusion criteria were postmenopausal participants aged 40 to 65 years experiencing 50 or more moderate to severe vasomotor symptoms over 7 days during screening.",
            "reason": "The study clearly states the inclusion criteria as "postmenopausal participants, aged 40 to 65 years and experiencing 50 or more moderate to severe VMS over 7 days during screening".",
            "verdict": 1
        },
        {
            "statement": "The key exclusions were participants with abnormal liver parameters, disordered proliferative endometrium, endometrial hyperplasia or polyps, current or history of malignancy within the last 5 years (except basal and squamous cell skin tumors).",
            "reason": "The study states the key exclusion criteria, including "abnormal liver parameters (including alanine aminotransferase or aspartate aminotransferase >2 × upper limit of normal), disordered proliferative endometrium, endometrial hyperplasia or polyps, and current or history of malignancy within the last 5 years (except basal and squamous cell skin tumors)."",
            "verdict": 1
        },
        {
            "statement": "The intervention was elinzanetant 120 mg once daily orally for 26 weeks (OASIS 1: n=199; OASIS 2: n=200).",
            "reason": "The study clearly states the intervention as "Once daily oral elinzanetant, 120 mg, for 26 weeks" for the elinzanetant group.",
            "verdict": 1
        },
        {
            "statement": "The comparator was matching placebo once daily orally for 12 weeks followed by elinzanetant 120 mg for 14 weeks (OASIS 1: n=197; OASIS 2: n=200).",
            "reason": "The study states the comparator as "matching placebo for 12 weeks followed by elinzanetant, 120 mg, for 14 weeks" for the placebo group.",
            "verdict": 1
        },
        {
            "statement": "The primary outcome was the mean change in frequency and severity of moderate to severe vasomotor symptoms from baseline to weeks 4 and 12 measured by the electronic hot flash daily diary.",
            "reason": "The study clearly states the primary outcomes as "mean change in frequency and severity of moderate to severe VMS from baseline to weeks 4 and 12, as measured by the electronic hot flash daily diary."",
            "verdict": 1
        },
        {
            "statement": "The secondary outcomes were changes in the Patient-Reported Outcomes Measurement Information System Sleep Disturbance Short Form 8b total T score and the Menopause-Specific Quality of Life questionnaire total score from baseline to week 12.",
            "reason": "The study states the secondary outcomes as "mean changes in the Patient-Reported Outcomes Measurement Information System Sleep Disturbance Short Form (PROMIS SD SF) 8b total T score and the Menopause-Specific Quality of Life (MENQOL) questionnaire total score from baseline to week 12."",
            "verdict": 1
        },
        {
            "statement": "The followup rates were 78.0% for OASIS 1 and 81.0% for OASIS 2, and the analysis was conducted on the full analysis set.",
            "reason": "The study reports the participant disposition, stating that "A total of 309 (78.0%) and 324 (81.0%) completed OASIS 1 and 2, respectively." It also states that "Efficacy analyses were performed on the full analysis set where all randomized participants were included."",
            "verdict": 1
        },
        {
            "statement": "The efficacy analyses were performed on the full analysis set where all randomized participants were included.",
            "reason": "The study explicitly states that "Efficacy analyses were performed on the full analysis set where all randomized participants were included."",
            "verdict": 1
        },
        {
            "statement": "The mean age was 54.6 years for OASIS 1 and 54.8 years for OASIS 2, and all participants were postmenopausal women.",
            "reason": "The study reports the baseline demographics, stating that the "mean (SD) age, OASIS 1: 54.6 (4.9) years; OASIS 2: 54.8 (5.0) years" and that all participants were postmenopausal.",
            "verdict": 1
        },
        {
            "statement": "The race or ethnicity was predominantly White with 12% to 19% Black or African American and less than 10% Hispanic or Latino.",
            "reason": "The study reports the race and ethnicity of the participants, stating that the population was "primarily White, with 12% to 19% Black or African American and less than 10% Hispanic or Latino."",
            "verdict": 1
        },
        {
            "statement": "The OASIS 1 and 2 trials were sponsored by Bayer.",
            "reason": "The study states that "The OASIS 1 and 2 trials were sponsored by Bayer."",
            "verdict": 1
        },
        {
            "statement": "Elinzanetant was found to be well tolerated and efficacious for the treatment of moderate to severe vasomotor symptoms associated with menopause, showing significant reductions in symptom frequency and severity compared to placebo along with improvements in sleep disturbances and menopause-related quality of life.",
            "reason": "The study results clearly demonstrate that elinzanetant was effective in reducing vasomotor symptom frequency and severity, improving sleep disturbances and menopause-related quality of life, and had a favorable safety profile compared to placebo.",
            "verdict": 1
        }
    ]
}
For troubleshooting, visit: https://python.langchain.com/docs/troubleshooting/errors/OUTPUT_PARSING_FAILURE )

In [ ]:
try:
    result = evaluate(
        llm=claude_3_haiku,
        dataset=dataset1,
        raise_exceptions=False,
        metrics=[faithfulness],
    )

    df = result.to_pandas()


except KeyError as e:
    print("Error during evaluation:", e)

Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

ERROR:ragas.executor:Exception raised in Job[0]: OutputParserException(Invalid json output: {
    "statements": [
        {
            "statement": "The study design was a randomized controlled trial.",
            "reason": "The passage states that this was a \"randomized controlled study, with parallel randomization (1:1:1)\".",
            "verdict": 1
        },
        {
            "statement": "The allocation concealment was achieved by using sequentially numbered sealed opaque envelopes.",
            "reason": "The passage mentions that \"Allocation was concealed in sequentially numbered, sealed, opaque envelopes.\"",
            "verdict": 1
        },
        {
            "statement": "The therapist who carried out the evaluation and treatment was not blinded.",
            "reason": "The passage states that \"The main limitation of our study was that the therapist that carried out the evaluation and treatment was not blinded and this could have influenced the results.\"",
            "verdict": 1
        },
        {
            "statement": "The follow-up duration was 12 months.",
            "reason": "The passage states that participants were evaluated \"before treatment, at the end, 3 and 12 months after treatment completion\".",
            "verdict": 1
        },
        {
            "statement": "The study setting was a single-center Federal University of São Carlos Brazil.",
            "reason": "The passage mentions that the study was performed \"in the Federal University of São Carlos, Brazil\".",
            "verdict": 1
        },
        {
            "statement": "The sample size was 45 postmenopausal women.",
            "reason": "The passage states that \"This study included post-menopausal women, defined by the absence of vaginal bleeding for 12 months\" and that \"Forty-five potential participants were screened and 45 met the criteria.\"",
            "verdict": 1
        },
        {
            "statement": "The inclusion criteria were: postmenopausal women defined by the absence of vaginal bleeding for 12 months, at least one episode of stress urinary incontinence (SUI) symptom during the previous month, and women who answered \"yes\" to the question about stress urinary incontinence in the King's Health Questionnaire.",
            "reason": "The passage clearly outlines the inclusion criteria, including the details mentioned in the statement.",
            "verdict": 1
        },
        {
            "statement": "The key exclusion criteria were: pelvic organ prolapse greater than grade II on Baden–Walker classification system, previous treatment for urinary incontinence or hormone therapy, ongoing urinary tract infections, cognitive or neurological disorders, and inability to perform the proposed procedures.",
            "reason": "The passage lists the key exclusion criteria, which match the details provided in the statement.",
            "verdict": 1
        },
        {
            "statement": "The intervention group received vaginal cones (VC, n=15) for pelvic floor muscle strengthening, with 12 sessions twice weekly for 6 weeks.",
            "reason": "The passage states that the VC group \"carried out the pelvic floor muscle strengthening with vaginal cones during the whole session\" and that the treatment \"consisted of 12 sessions, with two 40 min sessions per week and total of 6 weeks of treatment.\"",
            "verdict": 1
        },
        {
            "statement": "The comparator group received pelvic floor muscle training (PFMT, n=15) without vaginal cones, with the same schedule as the intervention group.",
            "reason": "The passage describes the PFMT group as receiving \"pelvic floor muscle training\" without the use of vaginal cones, and states that the treatment schedule was the same as the VC group.",
            "verdict": 1
        },
        {
            "statement": "The control group (CG, n=15) received no treatment during the corresponding time.",
            "reason": "The passage states that the "CG did not receive any treatment during the corresponding time."",
            "verdict": 1
        },
        {
            "statement": "The primary outcome was urinary leakage measured by the 1-hour pad test.",
            "reason": "The passage mentions that the "primary outcome (urinary leakage)" was evaluated using the "1-hr pad test".",
            "verdict": 1
        },
        {
            "statement": "The secondary outcomes were pelvic floor muscle strength measured using a Perina Stim device, quality of life assessed using the King's Health Questionnaire, satisfaction with treatment, and continuity of training.",
            "reason": "The passage lists the secondary outcomes as "pelvic floor muscle strength, quality of life, satisfaction with treatment and continuity of training", and provides details on the measurement methods.",
            "verdict": 1
        },
        {
            "statement": "41 participants completed the study, resulting in a 91.1% follow-up rate.",
            "reason": "The passage states that "Forty-one participants completed the study and were included in the analysis" out of the original 45 participants.",
            "verdict": 1
        },
        {
            "statement": "The analysis was conducted on those who completed the study, and no intention-to-treat analysis was performed.",
            "reason": "The passage indicates that the analysis was done on the 41 participants who completed the study, and does not mention any intention-to-treat analysis.",
            "verdict": 1
        },
        {
            "statement": "The mean age of the participants was approximately 62-64 years, and they were all postmenopausal women.",
            "reason": "The passage provides the age ranges for the three groups, which are all around 62-64 years, and states that the study included "post-menopausal women".",
            "verdict": 1
        },
        {
            "statement": "The sources of funding were not mentioned.",
            "reason": "The passage does not mention any information about the sources of funding for the study.",
            "verdict": 1
        },
        {
            "statement": "The conclusion was that treatments with and without vaginal cones can promote positive long-term effects on urinary leakage, pelvic floor muscle strength, and quality of life in postmenopausal women with SUI, and there were no significant differences between the groups in primary outcomes in any evaluations.",
            "reason": "The passage states in the conclusion that "Treatments with and without vaginal cones can promote positive long-term effects on urinary leakage, pelvic floor muscle strength and quality of life in post-menopausal women with SUI" and that "there were no differences between VC and PFMT group in primary outcome in any evaluations."",
            "verdict": 1
        },
        {
            "statement": "The main results showed that both the vaginal cones (VC) and pelvic floor muscle training (PFMT) groups had significantly better outcomes than the control group (CG) in terms of urinary leakage, pelvic floor muscle strength, and quality of life at the end of treatment, 3 months, and 12 months.",
            "reason": "The passage describes the main results, stating that both the VC and PFMT groups had significant improvements compared to the control group in the primary and secondary outcomes at the end of treatment, 3 months, and 12 months.",
            "verdict": 1
        },
        {
            "statement": "There were no reported adverse effects due to the treatments in either the VC or PFMT groups.",
            "reason": "The passage states that "There were no complaints of adverse effects due to the treatment from either group."",
            "verdict": 1
        }
    ]
}
For troubleshooting, visit: https://python.langchain.com/docs/troubleshooting/errors/OUTPUT_PARSING_FAILURE )

In [ ]:
try:
    result = evaluate(
        llm=gpt_5_1,
        dataset=dataset1,
        raise_exceptions=False,
        metrics=[faithfulness],
    )

    df = result.to_pandas()


except KeyError as e:
    print("Error during evaluation:", e)

Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
df # dee

,user_input,retrieved_contexts,response,reference,faithfulness
0,Extract structured PICO information from the R...,[doi: 10.1210/jc.2019-00677\nhttps://academic....,PICO variables\n1. Methods\n Design: Random...,Design: Randomized control trial\nDrug & dose ...,1.0

In [ ]:
try:
    result = evaluate(
        llm=gpt_5_1,
        dataset=dataset1,
        raise_exceptions=False,
        metrics=[faithfulness],
    )

    df = result.to_pandas()


except KeyError as e:
    print("Error during evaluation:", e)

Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
try:
    result = evaluate(
        llm=claude_3_haiku,
        dataset=dataset1,
        raise_exceptions=False,
        metrics=[faithfulness],
    )

    df = result.to_pandas()


except KeyError as e:
    print("Error during evaluation:", e)

Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

ERROR:ragas.executor:Exception raised in Job[0]: OutputParserException(Invalid json output: {
    "statements": [
        {
            "statement": "The study was a randomized controlled trial.",
            "reason": "The study design is clearly described as "randomized, double-blind, multinational, and placebo-controlled trials".",
            "verdict": 1
        },
        {
            "statement": "The study used a centralized interactive voice/web response system for randomization which indicates allocation concealment.",
            "reason": "The study states that "Randomization was performed centrally using an interactive voice/web response system and stratified by North America and the rest of the countries."",
            "verdict": 1
        },
        {
            "statement": "Investigators, participants, and study personnel remained blinded throughout the trials.",
            "reason": "The study explicitly states that "Investigators, participants, and study personnel remained blinded throughout the trials."",
            "verdict": 1
        },
        {
            "statement": "The followup duration was 26 weeks.",
            "reason": "The study design states that the trials were "26-week intervention trials".",
            "verdict": 1
        },
        {
            "statement": "The study was conducted at 77 sites in the US, Europe, and Israel for OASIS 1, and 77 sites in the US, Canada, and Europe for OASIS 2.",
            "reason": "The study states that "OASIS 1 was conducted between August 27, 2021, and November 27, 2023, across 77 sites in the US, Europe, and Israel. OASIS 2 was conducted between October 29, 2021, and October 10, 2023, across 77 sites in Canada, the US, and Europe."",
            "verdict": 1
        },
        {
            "statement": "The sample size was 796 participants (OASIS 1: 396; OASIS 2: 400).",
            "reason": "The study states that "400 Randomized" for OASIS 2 and "396 Randomized" for OASIS 1, totaling 796 participants.",
            "verdict": 1
        },
        {
            "statement": "The inclusion criteria were postmenopausal participants aged 40 to 65 years experiencing 50 or more moderate to severe vasomotor symptoms over 7 days during screening.",
            "reason": "The study clearly states the inclusion criteria as "postmenopausal participants, aged 40 to 65 years and experiencing 50 or more moderate to severe VMS over 7 days during screening".",
            "verdict": 1
        },
        {
            "statement": "The key exclusions were participants with abnormal liver parameters, disordered proliferative endometrium, endometrial hyperplasia or polyps, current or history of malignancy within the last 5 years (except basal and squamous cell skin tumors).",
            "reason": "The study states the key exclusion criteria, including "abnormal liver parameters (including alanine aminotransferase or aspartate aminotransferase >2 × upper limit of normal), disordered proliferative endometrium, endometrial hyperplasia or polyps, and current or history of malignancy within the last 5 years (except basal and squamous cell skin tumors)."",
            "verdict": 1
        },
        {
            "statement": "The intervention was elinzanetant 120 mg once daily orally for 26 weeks (OASIS 1: n=199; OASIS 2: n=200).",
            "reason": "The study clearly states the intervention as "Once daily oral elinzanetant, 120 mg, for 26 weeks" for the elinzanetant group.",
            "verdict": 1
        },
        {
            "statement": "The comparator was matching placebo once daily orally for 12 weeks followed by elinzanetant 120 mg for 14 weeks (OASIS 1: n=197; OASIS 2: n=200).",
            "reason": "The study states the comparator as "matching placebo for 12 weeks followed by elinzanetant, 120 mg, for 14 weeks" for the placebo group.",
            "verdict": 1
        },
        {
            "statement": "The primary outcome was the mean change in frequency and severity of moderate to severe vasomotor symptoms from baseline to weeks 4 and 12 measured by the electronic hot flash daily diary.",
            "reason": "The study clearly states the primary outcomes as "mean change in frequency and severity of moderate to severe VMS from baseline to weeks 4 and 12, as measured by the electronic hot flash daily diary."",
            "verdict": 1
        },
        {
            "statement": "The secondary outcomes were changes in the Patient-Reported Outcomes Measurement Information System Sleep Disturbance Short Form 8b total T score and the Menopause-Specific Quality of Life questionnaire total score from baseline to week 12.",
            "reason": "The study states the secondary outcomes as "mean changes in the Patient-Reported Outcomes Measurement Information System Sleep Disturbance Short Form (PROMIS SD SF) 8b total T score and the Menopause-Specific Quality of Life (MENQOL) questionnaire total score from baseline to week 12."",
            "verdict": 1
        },
        {
            "statement": "The followup rates were 78.0% for OASIS 1 and 81.0% for OASIS 2, and the analysis was conducted on the full analysis set.",
            "reason": "The study reports the participant disposition, stating that "A total of 309 (78.0%) and 324 (81.0%) completed OASIS 1 and 2, respectively." It also states that "Efficacy analyses were performed on the full analysis set where all randomized participants were included."",
            "verdict": 1
        },
        {
            "statement": "The efficacy analyses were performed on the full analysis set where all randomized participants were included.",
            "reason": "The study explicitly states that "Efficacy analyses were performed on the full analysis set where all randomized participants were included."",
            "verdict": 1
        },
        {
            "statement": "The mean age was 54.6 years for OASIS 1 and 54.8 years for OASIS 2, and all participants were postmenopausal women.",
            "reason": "The study reports the baseline demographics, stating that the "mean (SD) age, OASIS 1: 54.6 (4.9) years; OASIS 2: 54.8 (5.0) years" and that all participants were postmenopausal.",
            "verdict": 1
        },
        {
            "statement": "The race or ethnicity was predominantly White with 12% to 19% Black or African American and less than 10% Hispanic or Latino.",
            "reason": "The study reports the race and ethnicity of the participants, stating that the majority were White, with 12% to 19% Black or African American and less than 10% Hispanic or Latino.",
            "verdict": 1
        },
        {
            "statement": "The OASIS 1 and 2 trials were sponsored by Bayer.",
            "reason": "The study states that "The OASIS 1 and 2 trials were sponsored by Bayer."",
            "verdict": 1
        },
        {
            "statement": "Elinzanetant was found to be well tolerated and efficacious for the treatment of moderate to severe vasomotor symptoms associated with menopause, showing significant reductions in symptom frequency and severity compared to placebo along with improvements in sleep disturbances and menopause-related quality of life.",
            "reason": "The study results clearly demonstrate that elinzanetant was effective in reducing vasomotor symptom frequency and severity, improving sleep disturbances and menopause-related quality of life, and had a favorable safety profile compared to placebo.",
            "verdict": 1
        }
    ]
}
For troubleshooting, visit: https://python.langchain.com/docs/troubleshooting/errors/OUTPUT_PARSING_FAILURE )

In [ ]:
df # oasis

,user_input,retrieved_contexts,response,reference,faithfulness
0,Extract structured PICO information from the R...,[Elinzanetant for Vasomotor Symptoms Associate...,PICO variables\n1. Methods\n Design: Randomize...,Design: Randomized control trial\nDrug & dose ...,0.977273

In [ ]:
df # oasis

,user_input,retrieved_contexts,response,reference,faithfulness
0,Extract structured PICO information from the R...,[Elinzanetant for Vasomotor Symptoms Associate...,PICO variables\n1. Methods\n Design: Randomize...,Design: Randomized control trial\nDrug & dose ...,0.780303

In [ ]:
df # oasis

,user_input,retrieved_contexts,response,reference,faithfulness
0,Extract structured PICO information from the R...,[Elinzanetant for Vasomotor Symptoms Associate...,PICO variables\n1. Methods\n Design: Randomize...,Design: Randomized control trial\nDrug & dose ...,0.645833

In [ ]:
df # sky

,user_input,retrieved_contexts,response,reference,faithfulness
0,Extract structured PICO information from the R...,[Articles\nThe mixed model repeated measures u...,PICO variables\n1. Methods\n Design: Random...,Design: Randomized control trial\nDrug & dose ...,0.978495

In [ ]:
df # Oasis

,user_input,retrieved_contexts,response,reference,faithfulness
0,Extract structured PICO information from the R...,[Elinzanetant for Vasomotor Symptoms Associate...,PICO variables\n1. Methods\n Design: Randomize...,Design: Randomized control trial\nDrug & dose ...,1.0

In [ ]:
df # iLankoon

,user_input,retrieved_contexts,response,reference,faithfulness
0,Extract structured PICO information from the R...,[Page 4 of 9\nIlankoon et al. BMC Women’s Heal...,PICO variables\n1. Methods\n Design: Qualit...,"Country of Study: Colombo, Sri Lanka\nAim: To ...",1.0

In [ ]:
df # desalis

,user_input,retrieved_contexts,response,reference,faithfulness
0,Extract structured PICO information from the R...,"[540\nI. DE SALIS ET AL.\nStrauss, A. (1987). ...",PICO variables\nThe provided text does not des...,Country of Study:\nUK\nAim:\nTo explore the ex...,1.0

In [ ]:
df # Wang

,user_input,retrieved_contexts,response,reference,faithfulness
0,Extract structured PICO information from the R...,[1423\nWorld Journal of Urology (2019) 37:1421...,PICO variables\n1. Methods\n Design: Random...,1. Methods\nDesign: Randomized controlled tria...,1.0

In [ ]:
df # verschoor 3

,user_input,retrieved_contexts,response,reference,faithfulness
0,Extract structured PICO information from the R...,"[Journals of Gerontology: MEDICAL SCIENCES, 20...",PICO variables\n1. Methods\n Design: Crosss...,"Location: Canada\nSample Size: 15,320\nMean Ag...",1.0

In [ ]:
df # Verschoorn

,user_input,retrieved_contexts,response,reference,faithfulness
0,Extract structured PICO information from the R...,"[Journals of Gerontology: MEDICAL SCIENCES, 20...",PICO variables\n1. Methods\n Design: Crosss...,"Location: Canada\nSample Size: 15,320\nMean Ag...",1.0

In [ ]:
df # Simkin

,user_input,retrieved_contexts,response,reference,faithfulness
0,Extract structured PICO information from the R...,[214\nSimkin-Silverman et al.\nAnnals of Behav...,PICO variables\n1. Methods\n Design: Random...,Country: USA\nDesign: Randomized Controlled Tr...,1.0

In [ ]:
df # Pereira

,user_input,retrieved_contexts,response,reference,faithfulness
0,Extract structured PICO information from the R...,"[15206777, 2013, 1, Downloaded from https://on...",PICO variables\n1. Methods\n Design: Random...,1. Methods\nDesign: Randomized controlled tria...,1.0

In [ ]:
df # Ogwumike

,user_input,retrieved_contexts,response,reference,faithfulness
0,Extract structured PICO information from the R...,[Niger. J. Physiol. Sci. 26 (2011): Ogwumike e...,PICO variables\n1. Methods\n Design: Pretes...,Country: Nigeria\nDesign: RCT\nParticipants: 2...,1.0

In [ ]:
df # Lee

,user_input,retrieved_contexts,response,reference,faithfulness
0,Extract structured PICO information from the R...,[Y. Lee et al.\nArchives of Gerontology and Ge...,PICO variables\n1. Methods\n\n Design: Cros...,Location: South Korea\nSample Size: 1264\nMean...,1.0

In [ ]:
df # Leibaschoff 3.5

,user_input,retrieved_contexts,response,reference,faithfulness
0,Extract structured PICO information from the R...,[Gynecology\nSURGICAL TECHNOLOGY INTERNATIONAL...,PICO variables\n1. Methods\n Design: Prospe...,1. Methods\nDesign: Randomized controlled tria...,1.0

In [ ]:
df # Kojima 3.5 2nd

,user_input,retrieved_contexts,response,reference,faithfulness
0,Extract structured PICO information from the R...,"[15325415, 2022, 9, Downloaded from https://ag...",PICO variables\n1. Methods\n Design: Prospe...,\n\nLocation: UK\nSample size: 1249\nMean age ...,1.0

In [ ]:
df # Kojima 3

,user_input,retrieved_contexts,response,reference,faithfulness
0,Extract structured PICO information from the R...,"[15325415, 2022, 9, Downloaded from https://ag...",PICO variables\n1. Methods\n Design: Prospe...,\n\nLocation: UK\nSample size: 1249\nMean age ...,1.0

In [ ]:
df # haung 3 2nd

,user_input,retrieved_contexts,response,reference,faithfulness
0,Extract structured PICO information from the R...,"[15325415, 2018, 11, Downloaded from https://a...",PICO variables\n1. Methods\n Design: Prospe...,Location: US\nSample Size: 7699\nMean Age (Ran...,1.0

In [ ]:
df # haung 3

,user_input,retrieved_contexts,response,reference,answer_relevancy,faithfulness
0,Extract structured PICO information from the R...,"[15325415, 2018, 11, Downloaded from https://a...",PICO variables\n1. Methods\n Design: Prospe...,Location: US\nSample Size: 7699\nMean Age (Ran...,0.785281,1.0

In [ ]:
df # hanger 3

,user_input,retrieved_contexts,response,reference,answer_relevancy,faithfulness
0,Extract structured PICO information from the R...,"[HAGNER ET AL\n[HDL], low-density lipoprotein ...",PICO variables\n1. Methods\n Design: The st...,Country: Poland\nDesign: Pre/Post\nParticipant...,0.755984,1.0

In [ ]:
df # Capobiano 3.5

,user_input,retrieved_contexts,response,reference,answer_relevancy,faithfulness
0,Extract structured PICO information from the R...,[400\nArch Gynecol Obstet (2012) 285:397–403\n...,PICO variables\n1. Methods\n Design: Random...,\n1. Methods\nDesign: Randomized controlled tr...,0.740051,1.0

In [ ]:
df #worringer

,user_input,retrieved_contexts,response,reference,faithfulness,context_recall
0,Provide a comprehensive structured summary of ...,[Research Original Investigation\nAcetaminophe...,PICO variables\n1. Methods\n Design: Nation...,Methods\nDesign: Nationwide cohort study with ...,0.947368,0.904762

In [ ]:
df # Capobiano 3

,user_input,retrieved_contexts,response,reference,answer_relevancy,faithfulness
0,Extract structured PICO information from the R...,[400\nArch Gynecol Obstet (2012) 285:397–403\n...,PICO variables\n1. Methods\n Design: Random...,\n1. Methods\nDesign: Randomized controlled tr...,0.855731,1.0

In [ ]:
df # Bertotto 3 haiku 2nd time

,user_input,retrieved_contexts,response,reference,answer_relevancy,faithfulness
0,Extract structured PICO information from the R...,"[15206777, 2017, 8, Downloaded from https://on...",PICO variables\n1. Methods\n Design: Random...,1. Methods\nDesign: Randomized controlled tria...,0.822708,0.947368

In [ ]:
df # Bertotto 3.5

,user_input,retrieved_contexts,response,reference,answer_relevancy,faithfulness
0,Extract structured PICO information from the R...,"[15206777, 2017, 8, Downloaded from https://on...",PICO variables\n1. Methods\n Design: Random...,1. Methods\nDesign: Randomized controlled tria...,0.736125,1.0

In [ ]:
df # Bertotto

,user_input,retrieved_contexts,response,reference,answer_relevancy,faithfulness
0,Extract structured PICO information from the R...,"[15206777, 2017, 8, Downloaded from https://on...",PICO variables\n1. Methods\n Design: Random...,1. Methods\nDesign: Randomized controlled tria...,0.853318,0.95